# Generated by Django 3.2.20 on 2023-11-06 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('no_of_vacancy', models.IntegerField()),
                ('Vacancy_details', models.CharField(max_length=80)),
                ('Qualification', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=30)),
                ('op1', models.CharField(max_length=30)),
                ('op2', models.CharField(max_length=30)),
                ('op3', models.CharField(max_length=30)),
                ('op4', models.CharField(max_length=30)),
                ('VACANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=30)),
                ('ATTEND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.attendexam')),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to='')),
                ('qualification', models.CharField(max_length=30)),
                ('proof', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.login')),
            ],
        ),
        migrations.AddField(
            model_name='attendexam',
            name='CANDIDATE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.candidate'),
        ),
        migrations.AddField(
            model_name='attendexam',
            name='QUESTION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.question'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.candidate')),
                ('VACANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.vacancy')),
            ],
        ),
    ]
