# Generated by Django 3.2.20 on 2023-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Answers',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
