# Generated by Django 3.2.20 on 2023-11-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_question_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company_name',
            new_name='vacancy_name',
        ),
    ]
