# Generated by Django 3.2.20 on 2023-11-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_rename_company_name_vacancy_vacancy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
