# Generated by Django 3.2.20 on 2023-11-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_vacancy_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='HR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr_app.hr'),
            preserve_default=False,
        ),
    ]
