# Generated by Django 3.2.20 on 2023-11-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_vacancy_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendexam',
            old_name='result',
            new_name='Mark',
        ),
        migrations.AddField(
            model_name='interview',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
