# Generated by Django 3.2.20 on 2023-11-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_auto_20231107_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='company_name',
        ),
    ]
