# Generated by Django 3.2.20 on 2023-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_auto_20231108_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(max_length=300),
        ),
    ]
