# Generated by Django 3.2.20 on 2023-11-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0010_alter_question_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='score',
            field=models.CharField(max_length=30),
        ),
    ]
