# Generated by Django 3.2.22 on 2023-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0011_alter_interview_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tdate',
            field=models.DateField(default='2023-11-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='ttime',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
    ]
