# Generated by Django 3.2.22 on 2023-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0012_auto_20231119_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='deparment',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
